server:
  port: 10000
spring:
  security:
    user:
      name: user
      password: pass
  cloud:
    config:
      server:
        git:
          uri: https://github.com/psoap/spring-cloud
          clone-on-start: true
          search-paths: 'spring-cloud-config/config-files/'